# Generated by Django 6.0 on 2025-12-21 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('author', models.CharField(max_length=300, verbose_name='Автор')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('file', models.FileField(upload_to='books/', verbose_name='Файл книги')),
                ('flibusta_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Флибусты')),
                ('reading_progress', models.IntegerField(default=0, verbose_name='Прогресс чтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
    ]
