# Generated by Django 6.0 on 2025-12-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_read',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее чтение'),
        ),
    ]
